sudo: required
language: generic

services: 
    -docker

before_install:
    -docker build -t shivamgoyal312/docker-react -f Dockerfile.dev .
    -docker run -e CI=true shivamgoyal312/docker-react npm run test